[package]
name = "aws_greengrass_core_rust"
version = "0.1.11"
authors = ["Pete Matern <pete.matern@nike.com", "Jack Wright <jack.wright@nike.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.52.0"

[dependencies]
log = "^0.4"
lazy_static = "^1.4"
crossbeam-channel = "^0.4"
